# Generated by Django 4.1.2 on 2022-10-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='teacher',
            new_name='professor',
        ),
    ]
